- name: Log in to DockerHub
  run: |
    echo "Logging into DockerHub"
    echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

- name: Build Docker image manually (test)
  run: |
    echo "Building Docker image"
    docker build -t venkatalakshmi0448/my-image:latest .

- name: Push Docker image manually (test)
  run: |
    echo "Pushing Docker image to DockerHub"
    docker push venkatalakshmi0448/my-image:latest
