name: Validate Application Pipeline
on:
  push:
    branches:
      - main
  workflow_call:
    inputs:
      branch:
        description: 'Branch to validate'
        required: true
        type: string
        default: main
      dockerfile:
        description: 'Path to the Dockerfile'
        required: true
        type: string
        default: './Dockerfile'
      dockerhub_repo:
        description: 'Dockerhub repo name'
        required: true
        type: string
        default: 'venkatalakshmi0448/nodejs-docker'
      deploy_env:
        description: 'Deployment environment'
        required: true
        type: string
        default: 'staging'

jobs:
  validate:
    runs-on: ubuntu-latest
    environment:
      name: 'validate'
    
    strategy:
      matrix:
        step: ['checkout', 'docker-login', 'docker-build', 'docker-push']

    steps:
      # Checkout step
      - name: Checkout code
        if: matrix.step == 'checkout'
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.branch }}
        
      # Docker login step
      - name: Docker Login
        if: matrix.step == 'docker-login'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      # Docker build step
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        if: matrix.step == 'docker-build'
        run: |
              echo "Validating Docker build step"
              docker build -f ${{ inputs.dockerfile }} --progress=plain .

      # Docker push step
      - name: Push Docker image
        if: matrix.step == 'docker-push'
        run: |
             echo "Validating Docker push step"
             docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}
             echo "Pushing Docker image to DockerHub"
             docker push ${{ inputs.dockerhub_repo }}:latest
             docker push ${{ inputs.dockerhub_repo }}

  validate-environment:
    runs-on: ubuntu-latest
    steps:
      - name: Check if environment variables are set
        run: |
          echo "Validating Environment Variables"
          echo "DOCKERHUB_USERNAME = ${{ secrets.DOCKERHUB_USERNAME }}"
          echo "DOCKERHUB_PASSWORD = ${{ secrets.DOCKERHUB_PASSWORD }}"
