name: Deploy to Production
on:
  push:
    branches:
      - main
  pull_request:
     branches:
       - main
jobs:
  deploy-prod:
    runs-on: ubuntu-latest
      uses: Venkatalakshmi0448/nodejs-docker/.github/workflows/nodejs-image-build.yml@main
      with: 
        dockerfile: ./Dockerfile
        dockerhub_repo: venkatalakshmi0448/nodejs-docker
        deploy_env: prod
     secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
      KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
