name: Build and Push Docker Image
on:
  push:
    branches:
      - main
  workflow_call:
    inputs:
      dockerfile:
        description: 'Path to the Dockerfile'
        required: true
        type: string
        default: './Dockerfile'
      dockerhub_repo:
        description: 'Dockerhub repo name'
        required: true
        type: string
        default: 'venkatalakshmi0448/nodejs-docker'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Extract metadata (tags, labels) for docker
      id: meta
      uses: docker/metadata-action@v3
      with: 
         images: venkatalakshmi0448/nodejs-docker

    - name: Build and push Docker image
      uses: docker/build-push-action@v3
      with:
        context: .
        file: ${{ inputs.dockerfile }}  # Use `inputs.dockerfile` instead of `github.event.inputs.dockerfile`
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
